INSERT INTO `country` VALUES
  (1, 'Andorra'),
	(2, 'United Arab Emirates'),
	(3, 'Afghanistan'),
	(4, 'Antigua and Barbuda'),
	(5, 'Anguilla'),
	(6, 'Albania'),
	(7, 'Armenia'),
	(8, 'Netherlands Antilles'),
	(9, 'Angola'),
	(10, 'Argentina');

INSERT INTO `city` VALUES
  (NULL, 1, 'Aixas'),
	(NULL, 1, 'Aixirivali'),
	(NULL, 1, 'Aixirivall'),
	(NULL, 1, 'Aixirvall'),
	(NULL, 1, 'Aixovall'),
	(NULL, 1, 'Andorra'),
	(NULL, 1, 'Andorra la Vella'),
	(NULL, 1, 'Andorra-Vieille'),
	(NULL, 1, 'Andorre'),
	(NULL, 1, 'Andorre-la-Vieille'),
	(NULL, 2, 'Abu Dabi'),
	(NULL, 2, 'Abu Dhabi'),
	(NULL, 2, 'Abu Hail'),
	(NULL, 2, 'Abu Hayl'),
	(NULL, 2, 'Abu Zabi'),
	(NULL, 2, 'Abu Zaby'),
	(NULL, 2, 'Abu Zabye'),
	(NULL, 2, 'Abu Zabyo'),
	(NULL, 2, 'Ad Dharbaniya'),
	(NULL, 2, 'Ad Duss'),
  (NULL, 3, 'Abad'),
	(NULL, 3, 'Abaka'),
	(NULL, 3, 'Abak'),
	(NULL, 3, 'Abakeh'),
	(NULL, 3, 'Abakhel'),
	(NULL, 3, 'Abakheyl'),
	(NULL, 3, 'Abanda'),
	(NULL, 3, 'Aband'),
	(NULL, 3, 'Abas'),
	(NULL, 3, 'Abas'),
  (NULL, 4, 'Aberdeen'),
	(NULL, 4, 'Aberdeen Village'),
	(NULL, 4, 'All Saints'),
	(NULL, 4, 'All Saints Village'),
	(NULL, 4, 'Barnes Hill'),
	(NULL, 4, 'Barnes Hill Village'),
	(NULL, 4, 'Bats Cave'),
	(NULL, 4, 'Belmont'),
	(NULL, 4, 'Bendals'),
	(NULL, 4, 'Bendals Village'),
  (NULL, 5, 'Bethel'),
	(NULL, 5, 'Betty Hill'),
	(NULL, 5, 'Blowing Point Village'),
	(NULL, 5, 'Cannifist'),
	(NULL, 5, 'Cauls Bottom'),
	(NULL, 5, 'Chalvilles'),
	(NULL, 5, 'Crocus Hill'),
	(NULL, 5, 'Deep Waters'),
	(NULL, 5, 'East End'),
	(NULL, 5, 'East End Village'),
	(NULL, 5, 'Ebenezer'),
	(NULL, 6, 'Abat'),
	(NULL, 6, 'Abate'),
	(NULL, 6, 'Abati'),
	(NULL, 6, 'Abaz'),
	(NULL, 6, 'Abazaj'),
	(NULL, 6, 'Abaze'),
	(NULL, 6, 'Achmetaj'),
	(NULL, 6, 'Acmenik'),
	(NULL, 6, 'Ada'),
	(NULL, 6, 'Ad-Bunaca'),
  (NULL, 7, 'Abaran'),
	(NULL, 7, 'Abaran Verin'),
	(NULL, 7, 'Abilkend'),
	(NULL, 7, 'Abovyan'),
	(NULL, 7, 'Achadzhur'),
	(NULL, 7, 'Achajur'),
	(NULL, 7, 'Achanan'),
	(NULL, 7, 'Achasu'),
	(NULL, 7, 'Achkhlu'),
	(NULL, 7, 'Achpach'),
  (NULL, 8, 'Ararat'),
	(NULL, 8, 'Australie'),
	(NULL, 8, 'Barber'),
	(NULL, 8, 'Bau Seroe'),
	(NULL, 8, 'Bella Vista'),
	(NULL, 8, 'Bel Nem'),
	(NULL, 8, 'Belvedere'),
	(NULL, 8, 'Beneden Prinsen'),
	(NULL, 8, 'Beneden Prinsen Kwartier'),
	(NULL, 8, 'Benesuela'),
	(NULL, 8, 'Benners'),
  (NULL, 9, 'Abel Carapuchoso'),
	(NULL, 9, 'Abilio'),
	(NULL, 9, 'A. Braz'),
	(NULL, 9, 'Abreu'),
	(NULL, 9, 'Abreu'),
	(NULL, 9, 'A. Carvalho'),
	(NULL, 9, 'Aco'),
	(NULL, 9, 'Acucareira'),
	(NULL, 9, 'Acumba'),
	(NULL, 9, 'Acumba'),
	(NULL, 9, 'Adelina'),
  (NULL, 10, 'Abra Pampa'),
	(NULL, 10, 'Abra Rica'),
	(NULL, 10, 'A. Brown'),
	(NULL, 10, 'Acambuco'),
	(NULL, 10, 'A. Carboni'),
	(NULL, 10, 'Acassuso'),
	(NULL, 10, 'A. Castellanos'),
	(NULL, 10, 'A. Castro Tolay'),
	(NULL, 10, 'Acebal'),
	(NULL, 10, 'A. Ceballos'),
	(NULL, 10, 'Acequiones');